### PR TITLE
restrict month day numbers in date formats

### PR DESCRIPTION
**Pull request by mmoskal**
we could also check for leap year as well, there is the following in JsonSchemaStore ci.json:

```json
"released_at": {
              "type": "string",
              "description": "The date and time when the release is ready. Defaults to the current date and time if not defined. Should be enclosed in quotes and expressed in ISO 8601 format.",
              "format": "date-time",
              "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:Z|[+-][01]\\d:[0-5]\\d)$"
            },
```

but I think this will do for now

seems to pass the tests

### CODE REVIEW

**Comment by mmoskal** [comment]
@hudson-ai ping?

**Comment by hudson-ai** [comment]
Oh, my apologies for missing this PR! Will take a look and see how it changes coverage of the JSON Schema test suite date/datetime format tests. Is there a similar regex you can find for time?

**Comment by mmoskal** [comment]
I didn't get failures for time. Should be slightly better for the test suite.

**Comment by hudson-ai** [comment]
Looks great!

**Pull request merged**
